language: php
php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
